[project]
name = "postgres-db-backup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psycopg-binary>=3.2.9",
    "psycopg2>=2.9.10",
    "psycopg2-binary>=2.9.10",
    "pyyaml>=6.0.2",
]
